version: "3.9"
services:
  team-builder:
    image: blog-team-builder:dev
    build: ./
    container_name: team-builder
    restart: "no"
    network_mode: "host"
    env_file:
      - team-builder.env
